// This file is @generated by prost-build.
/// Color message with RGBA components
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Color {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Red component (0.0-1.0)
    #[prost(float, tag = "2")]
    pub r: f32,
    /// Green component (0.0-1.0)
    #[prost(float, tag = "3")]
    pub g: f32,
    /// Blue component (0.0-1.0)
    #[prost(float, tag = "4")]
    pub b: f32,
    /// Alpha component (0.0-1.0)
    #[prost(float, tag = "5")]
    pub a: f32,
    /// Optional color name
    #[prost(string, tag = "6")]
    pub name: ::prost::alloc::string::String,
}
/// Point message representing a 3D point with metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Point {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Point identifier/name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// X coordinate
    #[prost(double, tag = "3")]
    pub x: f64,
    /// Y coordinate
    #[prost(double, tag = "4")]
    pub y: f64,
    /// Z coordinate
    #[prost(double, tag = "5")]
    pub z: f64,
    /// Point diameter in pixels for display
    #[prost(double, tag = "6")]
    pub width: f64,
    /// Color of the point
    #[prost(message, optional, tag = "7")]
    pub pointcolor: ::core::option::Option<Color>,
}
/// Vector message representing a 3D vector
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vector {
    /// X component
    #[prost(double, tag = "1")]
    pub x: f64,
    /// Y component
    #[prost(double, tag = "2")]
    pub y: f64,
    /// Z component
    #[prost(double, tag = "3")]
    pub z: f64,
    /// Optional vector name
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
}
/// BoundingBox message representing an oriented bounding box
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BoundingBox {
    /// Center point of the box
    #[prost(message, optional, tag = "1")]
    pub center: ::core::option::Option<Point>,
    /// X-axis direction (orthogonal)
    #[prost(message, optional, tag = "2")]
    pub x_axis: ::core::option::Option<Vector>,
    /// Y-axis direction (orthogonal)
    #[prost(message, optional, tag = "3")]
    pub y_axis: ::core::option::Option<Vector>,
    /// Z-axis direction (orthogonal)
    #[prost(message, optional, tag = "4")]
    pub z_axis: ::core::option::Option<Vector>,
    /// Half-extents along each axis
    #[prost(message, optional, tag = "5")]
    pub half_size: ::core::option::Option<Vector>,
    /// Unique identifier
    #[prost(string, tag = "6")]
    pub guid: ::prost::alloc::string::String,
    /// Bounding box name
    #[prost(string, tag = "7")]
    pub name: ::prost::alloc::string::String,
}
/// Vertex data for mesh
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VertexData {
    #[prost(double, tag = "1")]
    pub x: f64,
    #[prost(double, tag = "2")]
    pub y: f64,
    #[prost(double, tag = "3")]
    pub z: f64,
    /// Custom vertex attributes
    #[prost(btree_map = "string, double", tag = "4")]
    pub attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
}
/// Hole ring (inner ring for face with holes)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HoleRing {
    #[prost(uint64, repeated, tag = "1")]
    pub vertices: ::prost::alloc::vec::Vec<u64>,
}
/// Face data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FaceData {
    /// Vertex indices in face
    #[prost(uint64, repeated, tag = "1")]
    pub vertices: ::prost::alloc::vec::Vec<u64>,
    /// Custom face attributes
    #[prost(btree_map = "string, double", tag = "2")]
    pub attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
    /// Inner rings (holes)
    #[prost(message, repeated, tag = "3")]
    pub holes: ::prost::alloc::vec::Vec<HoleRing>,
}
/// Edge data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EdgeData {
    #[prost(uint64, tag = "1")]
    pub vertex1: u64,
    #[prost(uint64, tag = "2")]
    pub vertex2: u64,
    /// Custom edge attributes
    #[prost(btree_map = "string, double", tag = "3")]
    pub attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
}
/// Flat triangle list (3 vertex keys per triangle)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TriList {
    #[prost(uint64, repeated, tag = "1")]
    pub vertices: ::prost::alloc::vec::Vec<u64>,
}
/// Mesh message representing a halfedge mesh data structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mesh {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Mesh name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// vertex_key -> VertexData
    #[prost(map = "uint64, message", tag = "3")]
    pub vertices: ::std::collections::HashMap<u64, VertexData>,
    /// face_key -> FaceData
    #[prost(map = "uint64, message", tag = "4")]
    pub faces: ::std::collections::HashMap<u64, FaceData>,
    /// Edge custom data
    #[prost(message, repeated, tag = "6")]
    pub edge_data: ::prost::alloc::vec::Vec<EdgeData>,
    /// Default vertex attrs
    #[prost(btree_map = "string, double", tag = "7")]
    pub default_vertex_attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
    /// Default face attrs
    #[prost(btree_map = "string, double", tag = "8")]
    pub default_face_attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
    /// Default edge attrs
    #[prost(btree_map = "string, double", tag = "9")]
    pub default_edge_attributes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
    /// Edge widths
    #[prost(double, repeated, tag = "13")]
    pub widths: ::prost::alloc::vec::Vec<f64>,
    /// Object color
    #[prost(message, optional, tag = "15")]
    pub objectcolor: ::core::option::Option<Color>,
    /// Active color mode (0=objectcolor,1=pointcolors,2=facecolors,3=none)
    #[prost(int32, tag = "16")]
    pub color_mode: i32,
    /// Face triangulation (face_key -> flat triangle vertex keys)
    #[prost(map = "uint64, message", tag = "17")]
    pub triangulation: ::std::collections::HashMap<u64, TriList>,
    /// ── P6: packed colour arrays, 4 floats per colour (r,g,b,a) ──
    /// `repeated Color` costs a sub-message per element carrying a 36-char guid String and a
    /// name — 66 B per colour against 16 B of actual data, and ~500-800k String allocations
    /// per sheet load. Packed float is bit-exact, memcpy-decodable and sliceable.
    ///
    /// Bulk colours carry NO guid and NO name. The guid was never identity — colour equality
    /// ignores it in all three languages and it is lazily minted. The name is always the
    /// default for bulk colours (every producer pushes Color::white()/black()); a Line, which
    /// CAN be named, keeps a zero-cost `linecolor_name` string instead.
    #[prost(float, repeated, tag = "18")]
    pub pointcolors_rgba: ::prost::alloc::vec::Vec<f32>,
    #[prost(float, repeated, tag = "19")]
    pub facecolors_rgba: ::prost::alloc::vec::Vec<f32>,
    #[prost(float, repeated, tag = "20")]
    pub linecolors_rgba: ::prost::alloc::vec::Vec<f32>,
}
/// NurbsSurface message representing a Non-Uniform Rational B-Spline surface
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NurbsSurface {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Surface name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Dimension (typically 3)
    #[prost(int32, tag = "3")]
    pub dimension: i32,
    /// Whether surface is rational (has weights)
    #[prost(bool, tag = "4")]
    pub is_rational: bool,
    /// Order in U direction (degree + 1)
    #[prost(int32, tag = "5")]
    pub order_u: i32,
    /// Order in V direction (degree + 1)
    #[prost(int32, tag = "6")]
    pub order_v: i32,
    /// Number of control vertices in U
    #[prost(int32, tag = "7")]
    pub cv_count_u: i32,
    /// Number of control vertices in V
    #[prost(int32, tag = "8")]
    pub cv_count_v: i32,
    /// Stride in U direction
    #[prost(int32, tag = "9")]
    pub cv_stride_u: i32,
    /// Stride in V direction
    #[prost(int32, tag = "10")]
    pub cv_stride_v: i32,
    /// NurbsKnot vector in U direction
    #[prost(double, repeated, tag = "11")]
    pub nurbsknots_u: ::prost::alloc::vec::Vec<f64>,
    /// NurbsKnot vector in V direction
    #[prost(double, repeated, tag = "12")]
    pub nurbsknots_v: ::prost::alloc::vec::Vec<f64>,
    /// Control vertices (flat array)
    #[prost(double, repeated, tag = "13")]
    pub cvs: ::prost::alloc::vec::Vec<f64>,
    /// Line width for display
    #[prost(double, tag = "14")]
    pub width: f64,
    /// Point colors (RGBA)
    #[prost(message, repeated, tag = "15")]
    pub pointcolors: ::prost::alloc::vec::Vec<Color>,
    /// Face colors (RGBA)
    #[prost(message, repeated, tag = "19")]
    pub facecolors: ::prost::alloc::vec::Vec<Color>,
    /// Line colors (RGBA)
    #[prost(message, repeated, tag = "20")]
    pub linecolors: ::prost::alloc::vec::Vec<Color>,
    /// Cached tessellation mesh
    #[prost(message, optional, tag = "21")]
    pub cached_mesh: ::core::option::Option<Mesh>,
}
/// NurbsCurve message representing a Non-Uniform Rational B-Spline curve
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NurbsCurve {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Curve name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Dimension (typically 3)
    #[prost(int32, tag = "3")]
    pub dimension: i32,
    /// Whether curve is rational (has weights)
    #[prost(bool, tag = "4")]
    pub is_rational: bool,
    /// Order of the curve (degree + 1)
    #[prost(int32, tag = "5")]
    pub order: i32,
    /// Number of control vertices
    #[prost(int32, tag = "6")]
    pub cv_count: i32,
    /// Stride between control points
    #[prost(int32, tag = "7")]
    pub cv_stride: i32,
    /// NurbsKnot vector
    #[prost(double, repeated, tag = "8")]
    pub nurbsknots: ::prost::alloc::vec::Vec<f64>,
    /// Control vertices (flat array)
    #[prost(double, repeated, tag = "9")]
    pub cvs: ::prost::alloc::vec::Vec<f64>,
    /// Line width for display
    #[prost(double, tag = "10")]
    pub width: f64,
    /// Point colors (RGBA)
    #[prost(message, repeated, tag = "11")]
    pub pointcolors: ::prost::alloc::vec::Vec<Color>,
    /// Line colors (RGBA)
    #[prost(message, repeated, tag = "13")]
    pub linecolors: ::prost::alloc::vec::Vec<Color>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BRepVertex {
    #[prost(int32, tag = "1")]
    pub point_index: i32,
    #[prost(int32, repeated, tag = "2")]
    pub edge_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BRepEdge {
    #[prost(int32, tag = "1")]
    pub curve_3d_index: i32,
    #[prost(int32, tag = "2")]
    pub start_vertex: i32,
    #[prost(int32, tag = "3")]
    pub end_vertex: i32,
    #[prost(int32, repeated, tag = "4")]
    pub trim_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BRepTrim {
    #[prost(int32, tag = "1")]
    pub curve_2d_index: i32,
    #[prost(int32, tag = "2")]
    pub edge_index: i32,
    #[prost(int32, tag = "3")]
    pub loop_index: i32,
    #[prost(bool, tag = "4")]
    pub reversed: bool,
    #[prost(enumeration = "BRepTrimType", tag = "5")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BRepLoop {
    #[prost(int32, repeated, tag = "1")]
    pub trim_indices: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "2")]
    pub face_index: i32,
    #[prost(enumeration = "BRepLoopType", tag = "3")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BRepFace {
    #[prost(int32, tag = "1")]
    pub surface_index: i32,
    #[prost(int32, repeated, tag = "2")]
    pub loop_indices: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag = "3")]
    pub reversed: bool,
    #[prost(message, optional, tag = "4")]
    pub facecolor: ::core::option::Option<Color>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BRep {
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub curves_2d: ::prost::alloc::vec::Vec<NurbsCurve>,
    #[prost(message, repeated, tag = "4")]
    pub curves_3d: ::prost::alloc::vec::Vec<NurbsCurve>,
    #[prost(message, repeated, tag = "5")]
    pub surfaces: ::prost::alloc::vec::Vec<NurbsSurface>,
    #[prost(message, repeated, tag = "6")]
    pub vertices: ::prost::alloc::vec::Vec<Point>,
    #[prost(message, repeated, tag = "7")]
    pub topology_vertices: ::prost::alloc::vec::Vec<BRepVertex>,
    #[prost(message, repeated, tag = "8")]
    pub topology_edges: ::prost::alloc::vec::Vec<BRepEdge>,
    #[prost(message, repeated, tag = "9")]
    pub trims: ::prost::alloc::vec::Vec<BRepTrim>,
    #[prost(message, repeated, tag = "10")]
    pub loops: ::prost::alloc::vec::Vec<BRepLoop>,
    #[prost(message, repeated, tag = "11")]
    pub faces: ::prost::alloc::vec::Vec<BRepFace>,
    #[prost(double, tag = "12")]
    pub width: f64,
    #[prost(message, optional, tag = "13")]
    pub surfacecolor: ::core::option::Option<Color>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BRepTrimType {
    TrimBoundary = 0,
    TrimMated = 1,
    TrimSeam = 2,
    TrimSingular = 3,
}
impl BRepTrimType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TrimBoundary => "TRIM_BOUNDARY",
            Self::TrimMated => "TRIM_MATED",
            Self::TrimSeam => "TRIM_SEAM",
            Self::TrimSingular => "TRIM_SINGULAR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRIM_BOUNDARY" => Some(Self::TrimBoundary),
            "TRIM_MATED" => Some(Self::TrimMated),
            "TRIM_SEAM" => Some(Self::TrimSeam),
            "TRIM_SINGULAR" => Some(Self::TrimSingular),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BRepLoopType {
    LoopOuter = 0,
    LoopInner = 1,
}
impl BRepLoopType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::LoopOuter => "LOOP_OUTER",
            Self::LoopInner => "LOOP_INNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOOP_OUTER" => Some(Self::LoopOuter),
            "LOOP_INNER" => Some(Self::LoopInner),
            _ => None,
        }
    }
}
/// Edge message representing a graph edge
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Edge {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Edge name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// First vertex identifier
    #[prost(string, tag = "3")]
    pub v0: ::prost::alloc::string::String,
    /// Second vertex identifier
    #[prost(string, tag = "4")]
    pub v1: ::prost::alloc::string::String,
    /// Edge attribute data as string
    #[prost(string, tag = "5")]
    pub attribute: ::prost::alloc::string::String,
    /// Integer index for the edge
    #[prost(int32, tag = "6")]
    pub index: i32,
}
/// Polyline message representing a connected sequence of points
/// Stores coordinates as a flat array \[x0, y0, z0, x1, y1, z1, ...\] for efficiency
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Polyline {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Polyline name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Flat array of coordinates \[x0, y0, z0, x1, y1, z1, ...\]
    #[prost(double, repeated, tag = "3")]
    pub coords: ::prost::alloc::vec::Vec<f64>,
    /// Line width
    #[prost(double, tag = "4")]
    pub width: f64,
    /// Line color
    #[prost(message, optional, tag = "5")]
    pub linecolor: ::core::option::Option<Color>,
    /// Dash pattern: on/off lengths in mm, repeating; empty = solid
    #[prost(double, repeated, tag = "7")]
    pub dash: ::prost::alloc::vec::Vec<f64>,
}
/// One modification applied to a host element - a cut, a drill, a joint pocket.
///
/// This is the serializable half of what `Element::add_feature` never could be: that takes a
/// std::function<Mesh(Mesh)>, so a feature applied in memory vanished the moment the Session
/// was written. Domains worked around it by adding their own flat arrays to Element - which is
/// how `joint_types` (one int per face) ended up in this file, and why it had to be reserved
/// out again. An ElementFeature carries the same information in a shape every domain can use: what the
/// modification is, which face it lands on, and the outlines it cuts.
///
/// The kernel does not know how to APPLY one; `feature_type` means something only to the
/// package that wrote it. It does know enough to draw it, which is what lets a viewer show
/// features from a package it has never heard of.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementFeature {
    /// Human-readable label
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// What kind of modification, e.g. "cut", "drill", "joint"
    #[prost(string, tag = "2")]
    pub feature_type: ::prost::alloc::string::String,
    /// Face of the host this applies to; -1 = the whole element
    #[prost(int32, tag = "3")]
    pub face_index: i32,
    /// Geometry of the modification
    #[prost(message, repeated, tag = "4")]
    pub outlines: ::prost::alloc::vec::Vec<Polyline>,
}
/// Element message wrapping geometry with metadata.
///
/// An Element is a geometry container and nothing more: a name, a guid, and one serialized
/// geometry payload. The Beam/Column/Plate kinds and their timber-joinery fields were removed
/// (see below) — an Element no longer knows what it "is", only what geometry it holds.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Element {
    /// Element name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// Class name for polymorphic decode
    #[prost(string, tag = "3")]
    pub geometry_type: ::prost::alloc::string::String,
    /// Serialized geometry bytes
    #[prost(bytes = "vec", tag = "4")]
    pub geometry_data: ::prost::alloc::vec::Vec<u8>,
    /// Class name of the DERIVED element, for polymorphic decode - the element's own type,
    /// where `geometry_type` above is the type of the geometry it holds. Empty means a plain
    /// Element, so proto3 omits it and a base element's bytes are unchanged by this field.
    ///
    /// The kernel does not know what any of these names mean. A downstream package (wood's
    /// plate, say) registers a factory under its own name; the loader looks the name up and
    /// hands the factory the bytes. That is what lets a domain type round-trip through a
    /// Session without the kernel growing a single domain-specific field - which is exactly
    /// what the removals above were for.
    #[prost(string, tag = "10")]
    pub element_type: ::prost::alloc::string::String,
    /// The derived type's own payload, encoded by whoever registered `element_type`. Opaque
    /// here on purpose: the kernel copies it through untouched, so a viewer that knows only
    /// `geometry_data` keeps working against files written by a package it has never heard of.
    #[prost(bytes = "vec", tag = "11")]
    pub element_data: ::prost::alloc::vec::Vec<u8>,
    /// Direction the element is inserted along when the assembly is put together. General to any
    /// assembly, not just joinery: it is what an assembly sequence is ordered by. Plural because
    /// an element with several jointed faces can admit a different direction per face.
    #[prost(message, repeated, tag = "12")]
    pub insertion_vectors: ::prost::alloc::vec::Vec<Vector>,
    /// NOMINAL extents in the element's own frame - authored design intent, NOT a measurement.
    /// For a plate x/y are the outline extent and z is the thickness; for a beam x/y are the
    /// cross-section and z the length. One field, both domains.
    ///
    /// Deliberately distinct from `Element::obb()`, which MEASURES the geometry that exists.
    /// These two are allowed to disagree: thickness drives a loft before there is any geometry to
    /// measure, so the nominal value has to exist first and outlive whatever is built from it.
    /// Read obb() when you want to know how big the thing is; read this when you want to know how
    /// big it was meant to be.
    #[prost(message, optional, tag = "13")]
    pub dimensions: ::core::option::Option<Vector>,
    /// Modifications applied to this element. Replaces the per-domain arrays that used to live in
    /// fields 6-9 - a joint type code is a feature on a face, which is what those were spelling
    /// out one array at a time.
    #[prost(message, repeated, tag = "14")]
    pub features: ::prost::alloc::vec::Vec<ElementFeature>,
}
/// Encoders message for serialization metadata and options
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncoderOptions {
    /// Pretty-print format (for JSON compatibility)
    #[prost(bool, tag = "1")]
    pub pretty: bool,
    /// Indentation level
    #[prost(int32, tag = "2")]
    pub indent: i32,
    /// Format type ("json", "protobuf", etc.)
    #[prost(string, tag = "3")]
    pub format: ::prost::alloc::string::String,
    /// Enable compression
    #[prost(bool, tag = "4")]
    pub compress: bool,
}
/// Generic serialized data container
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SerializedData {
    /// Type name of serialized object
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    /// Serialized binary data
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Encoding options used
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<EncoderOptions>,
    /// Serialization format version
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
}
/// Vertex message representing a graph vertex
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Vertex {
    /// Vertex name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// Vertex attribute data as string
    #[prost(string, tag = "3")]
    pub attribute: ::prost::alloc::string::String,
    /// Integer index for the vertex
    #[prost(int32, tag = "4")]
    pub index: i32,
}
/// Graph message representing a graph data structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Graph {
    /// Graph name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// vertex_name -> Vertex
    #[prost(btree_map = "string, message", tag = "3")]
    pub vertices: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        Vertex,
    >,
    /// List of edges
    #[prost(message, repeated, tag = "4")]
    pub edges: ::prost::alloc::vec::Vec<Edge>,
    /// Vertex counter
    #[prost(int32, tag = "5")]
    pub vertex_count: i32,
    /// Edge counter
    #[prost(int32, tag = "6")]
    pub edge_count: i32,
}
/// Xform message representing a 4x4 transformation matrix
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Xform {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Transformation name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 16 values in column-major order
    #[prost(double, repeated, tag = "3")]
    pub matrix: ::prost::alloc::vec::Vec<f64>,
}
/// InstanceRef message: a block reference that places a definition by a transform
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstanceRef {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Instance name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Guid of the definition this instance places
    #[prost(string, tag = "3")]
    pub definition_guid: ::prost::alloc::string::String,
    /// Placement transform (the only per-instance data)
    #[prost(message, optional, tag = "4")]
    pub xform: ::core::option::Option<Xform>,
    /// Per-instance color override
    #[prost(message, optional, tag = "5")]
    pub color: ::core::option::Option<Color>,
    /// Reserved: selection / cull / visibility
    #[prost(uint32, tag = "6")]
    pub flags: u32,
}
/// Line message representing a line segment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Line {
    /// Unique identifier
    #[prost(string, tag = "3")]
    pub guid: ::prost::alloc::string::String,
    /// Line name
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    /// Line width
    #[prost(double, tag = "6")]
    pub width: f64,
    /// Dash pattern: on/off lengths in mm, repeating; empty = solid
    #[prost(double, repeated, tag = "8")]
    pub dash: ::prost::alloc::vec::Vec<f64>,
    /// ── P6: the two hot fields, flattened ──
    /// A Line is the most numerous object in a drawing sheet (89,835 in one measured file,
    /// 178 B each on the wire for 48 B of data), so its per-object overhead IS the sheet
    /// load cost — and that cost is per-OBJECT, not per-byte: sheets decode at 95 ms/MB
    /// against 28 ms/MB for a point cloud, the difference being String and sub-message
    /// allocation.
    ///
    /// coords: \[x0,y0,z0,x1,y1,z1\] packed, replacing the two `Point` sub-messages. The kernel
    /// stores flat _x0.._z1 and never held Points at all — they were serialization-only
    /// wrappers, and each also carried a redundant `width: 1.0` fixed64.
    ///
    /// linecolor_rgba: 4 packed floats. The `Color` sub-message carried a 36-char guid String
    /// (~38 B) for a colour whose equality ignores the guid — dropped outright.
    ///
    /// linecolor_name: colour equality DOES compare the name, so it needs a home. proto3 omits
    /// an empty string entirely, so the default ("my_color") costs ZERO bytes on the wire —
    /// which is every line in a drawing sheet. Only a deliberately named colour pays, and it
    /// pays 8 bytes instead of a whole sub-message.
    #[prost(double, repeated, tag = "9")]
    pub coords: ::prost::alloc::vec::Vec<f64>,
    #[prost(float, repeated, tag = "10")]
    pub linecolor_rgba: ::prost::alloc::vec::Vec<f32>,
    #[prost(string, tag = "11")]
    pub linecolor_name: ::prost::alloc::string::String,
}
/// Matrix message representing an NxM matrix
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Matrix {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Matrix name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Number of rows
    #[prost(int32, tag = "3")]
    pub rows: i32,
    /// Number of columns
    #[prost(int32, tag = "4")]
    pub cols: i32,
    /// Row-major flat data, length = rows * cols
    #[prost(double, repeated, tag = "5")]
    pub data: ::prost::alloc::vec::Vec<f64>,
}
/// NurbsSurfaceTrimmed message representing a NURBS surface with trim boundaries
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NurbsSurfaceTrimmed {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Surface name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Underlying untrimmed surface
    #[prost(message, optional, tag = "3")]
    pub surface: ::core::option::Option<NurbsSurface>,
    /// Outer trim boundary (2D UV curve)
    #[prost(message, optional, tag = "4")]
    pub outer_loop: ::core::option::Option<NurbsCurve>,
    /// Inner trim loops (holes, 2D UV curves)
    #[prost(message, repeated, tag = "5")]
    pub inner_loops: ::prost::alloc::vec::Vec<NurbsCurve>,
    /// Line width for display
    #[prost(double, tag = "6")]
    pub width: f64,
    /// Surface color
    #[prost(message, optional, tag = "7")]
    pub surfacecolor: ::core::option::Option<Color>,
}
/// Plane message representing a 3D plane with minimal storage
/// Uses flat frame array: \[ox, oy, oz, xx, xy, xz, yx, yy, yz, zx, zy, zz\]
/// Plane equation coefficients (a, b, c, d) are computed from z_axis and origin
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Plane {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Plane name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Frame: origin(3) + x_axis(3) + y_axis(3) + z_axis(3) = 12 doubles
    #[prost(double, repeated, tag = "3")]
    pub frame: ::prost::alloc::vec::Vec<f64>,
    /// Width for plane visualization
    #[prost(double, tag = "4")]
    pub width: f64,
    /// Color of the plane
    #[prost(message, optional, tag = "6")]
    pub linecolor: ::core::option::Option<Color>,
}
/// PointCloud message representing a collection of 3D points with optional colors and normals
/// Stores data as flat arrays for efficient serialization
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PointCloud {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// PointCloud name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Flat array of coordinates \[x0, y0, z0, x1, y1, z1, ...\]
    #[prost(double, repeated, tag = "3")]
    pub coords: ::prost::alloc::vec::Vec<f64>,
    /// Flat array of colors \[r0, g0, b0, a0, r1, g1, b1, a1, ...\]
    #[prost(uint32, repeated, tag = "4")]
    pub colors: ::prost::alloc::vec::Vec<u32>,
    /// Flat array of normals \[nx0, ny0, nz0, nx1, ny1, nz1, ...\]
    #[prost(double, repeated, tag = "5")]
    pub normals: ::prost::alloc::vec::Vec<f64>,
    /// Point size for display
    #[prost(double, tag = "6")]
    pub point_size: f64,
}
/// Component message for custom domain objects (e.g. FloorBuilder, WallBuilder)
/// Allows external packages to store arbitrary serializable objects in a Session.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Component {
    /// class name, e.g. "FloorBuilder"
    #[prost(string, tag = "1")]
    pub type_name: ::prost::alloc::string::String,
    /// unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// human-readable name
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// custom fields serialized as JSON string
    #[prost(string, tag = "4")]
    pub json_data: ::prost::alloc::string::String,
}
/// Objects message representing a collection of all geometry types
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Objects {
    /// Objects collection name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// Collection of points
    #[prost(message, repeated, tag = "3")]
    pub points: ::prost::alloc::vec::Vec<Point>,
    /// Collection of lines
    #[prost(message, repeated, tag = "4")]
    pub lines: ::prost::alloc::vec::Vec<Line>,
    /// Collection of planes
    #[prost(message, repeated, tag = "5")]
    pub planes: ::prost::alloc::vec::Vec<Plane>,
    /// Collection of bounding boxes
    #[prost(message, repeated, tag = "6")]
    pub bboxes: ::prost::alloc::vec::Vec<BoundingBox>,
    /// Collection of polylines
    #[prost(message, repeated, tag = "7")]
    pub polylines: ::prost::alloc::vec::Vec<Polyline>,
    /// Collection of point clouds
    #[prost(message, repeated, tag = "8")]
    pub pointclouds: ::prost::alloc::vec::Vec<PointCloud>,
    /// Collection of meshes
    #[prost(message, repeated, tag = "9")]
    pub meshes: ::prost::alloc::vec::Vec<Mesh>,
    /// Collection of NURBS curves
    #[prost(message, repeated, tag = "12")]
    pub nurbscurves: ::prost::alloc::vec::Vec<NurbsCurve>,
    /// Collection of NURBS surfaces
    #[prost(message, repeated, tag = "13")]
    pub nurbssurfaces: ::prost::alloc::vec::Vec<NurbsSurface>,
    /// Collection of BReps
    #[prost(message, repeated, tag = "14")]
    pub breps: ::prost::alloc::vec::Vec<BRep>,
    /// Collection of elements
    #[prost(message, repeated, tag = "15")]
    pub elements: ::prost::alloc::vec::Vec<Element>,
    /// Collection of custom domain objects
    #[prost(message, repeated, tag = "16")]
    pub components: ::prost::alloc::vec::Vec<Component>,
}
/// Quaternion message for representing rotations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Quaternion {
    /// Scalar/real part
    #[prost(double, tag = "1")]
    pub a: f64,
    /// i component
    #[prost(double, tag = "2")]
    pub b: f64,
    /// j component
    #[prost(double, tag = "3")]
    pub c: f64,
    /// k component
    #[prost(double, tag = "4")]
    pub d: f64,
    /// Optional quaternion name
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
}
/// TreeNode message representing a node in a tree hierarchy
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TreeNode {
    /// Unique identifier for the node itself
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Node name (or geometry GUID if it's a geometry node)
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// GUID of parent node (empty for root)
    #[prost(string, tag = "3")]
    pub parent_guid: ::prost::alloc::string::String,
    /// Child nodes
    #[prost(message, repeated, tag = "4")]
    pub children: ::prost::alloc::vec::Vec<TreeNode>,
    /// Optional display color (used for layer nodes)
    #[prost(message, optional, tag = "5")]
    pub color: ::core::option::Option<Color>,
}
/// Tree message representing a hierarchical tree structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tree {
    /// Unique identifier
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// Tree name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Root node of the tree
    #[prost(message, optional, tag = "3")]
    pub root: ::core::option::Option<TreeNode>,
}
/// One object's local placement. Transforms are stored ONLY here - geometry types
/// carry no transformation member. A map is deliberately avoided: map iteration
/// order is unspecified, and this repo requires byte-identical output across languages.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct XformEntry {
    /// Guid of the object this transform places
    #[prost(string, tag = "1")]
    pub guid: ::prost::alloc::string::String,
    /// LOCAL transform, relative to the tree parent
    #[prost(message, optional, tag = "2")]
    pub xform: ::core::option::Option<Xform>,
}
/// Session message representing a complete session with geometry and hierarchy
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    /// Session name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// Collection of all geometry objects
    #[prost(message, optional, tag = "3")]
    pub objects: ::core::option::Option<Objects>,
    /// Tree hierarchy structure
    #[prost(message, optional, tag = "4")]
    pub tree: ::core::option::Option<Tree>,
    /// Graph relationships
    #[prost(message, optional, tag = "5")]
    pub graph: ::core::option::Option<Graph>,
    /// Simplified BVH representation (AABBs)
    #[prost(message, repeated, tag = "6")]
    pub bvh_boxes: ::prost::alloc::vec::Vec<BoundingBox>,
    /// Local transforms in Session::order() sequence, identity omitted
    #[prost(message, repeated, tag = "7")]
    pub xforms: ::prost::alloc::vec::Vec<XformEntry>,
}
/// Tolerance message for geometric comparisons
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tolerance {
    /// Unit system (e.g., "M", "MM")
    #[prost(string, tag = "1")]
    pub unit: ::prost::alloc::string::String,
    /// Absolute tolerance value
    #[prost(double, tag = "2")]
    pub absolute: f64,
    /// Relative tolerance value
    #[prost(double, tag = "3")]
    pub relative: f64,
    /// Angular tolerance in radians
    #[prost(double, tag = "4")]
    pub angular: f64,
    /// Approximation tolerance
    #[prost(double, tag = "5")]
    pub approximation: f64,
    /// Decimal precision for formatting
    #[prost(int32, tag = "6")]
    pub precision: i32,
    /// Linear deflection value
    #[prost(double, tag = "7")]
    pub lineardeflection: f64,
    /// Angular deflection value
    #[prost(double, tag = "8")]
    pub angulardeflection: f64,
}
