//! Cross-language geometry library with Point, Color, and Vector types.
//! Supports JSON serialization for interoperability between Rust, Python, and C++.

// Module declarations - makes modules publicly accessible
// Usage: session_rust::point::Point
#![allow(static_mut_refs)]

pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/session_proto.rs"));
}

pub mod aabb;
pub mod aabb_test;
pub mod guid_serde;
pub mod obb;
pub mod brep;
pub mod brep_test;
pub mod element;
pub mod element_test;
pub mod bvh;
pub mod bvh_test;
pub mod closest;
pub mod closest_test;
pub mod color;
pub mod encoders;
pub mod encoders_test;
pub mod graph;
pub mod intersection;
pub mod intersection_test;
pub mod knot;
pub mod knot_test;
pub mod line;
pub mod mesh;
pub mod mesh_iso;
pub mod nurbscurve;
pub mod nurbssurface;
pub mod obj;
pub mod obj_test;
pub mod remesh_cdt;
pub mod remesh_cdt_test;
pub mod trimmedsurface;
pub mod trimmedsurface_test;
pub mod objects;
pub mod plane;
pub mod point;
pub mod pointcloud;
pub mod polyline;
pub mod boolean_polyline;
pub mod primitives;
pub mod quaternion;
pub mod remesh_nurbssurface_adaptive;
pub mod remesh_nurbssurface_adaptive_test;
pub mod remesh_nurbssurface_grid;
pub mod remesh_nurbssurface_grid_test;
pub mod rtree;
pub mod rtree_test;
pub mod session;
pub mod session_config;
pub mod tolerance;
pub mod tree;
pub mod treenode;
pub mod vector;
pub mod xform;
pub mod mini_test;
pub mod color_test;
pub mod point_test;
pub mod vector_test;
pub mod session_config_test;
pub mod tolerance_test;
pub mod line_test;
pub mod polyline_test;
pub mod plane_test;
pub mod pointcloud_test;
pub mod xform_test;
pub mod mesh_test;
pub mod nurbscurve_test;
pub mod nurbssurface_test;
pub mod mesh_iso_test;
pub mod primitives_test;
pub mod session_test;
pub mod quaternion_test;
pub mod obb_test;
pub mod graph_test;
pub mod objects_test;
pub mod tree_test;
pub mod treenode_test;
pub mod matrix;
pub mod matrix_test;
pub mod convex_hull;
pub mod convex_hull_test;
pub mod kdtree;
pub mod kdtree_test;
pub mod marching_squares;
pub mod marching_squares_test;
pub mod boolean_polyline_test;

pub use aabb::AABB;
pub use obb::OBB;
pub use brep::BRep;
pub use bvh::BVH;
pub use closest::Closest;
pub use color::Color;
pub use element::Element;
pub use graph::{Edge, Graph};
pub use line::Line;
pub use mesh::{Mesh, LoftPanel, LoftWallFace};
pub use nurbscurve::NurbsCurve;
pub use nurbssurface::NurbsSurface;
pub use trimmedsurface::TrimmedSurface;
pub use obj::{read_obj, write_obj, read_obj_polylines, pair_polylines};
pub use objects::Objects;
pub use plane::Plane;
pub use point::Point;
pub use pointcloud::PointCloud;
pub use polyline::Polyline;
pub use mesh_iso::{MeshIso, TpmsType, TpmsMode};
pub use primitives::Primitives;
pub use quaternion::Quaternion;
pub use remesh_nurbssurface_adaptive::RemeshNurbsSurfaceAdaptive;
pub use remesh_nurbssurface_grid::remesh_nurbssurface_grid;
pub use rtree::RTree;
pub use session::{Geometry, Session};
pub use session_config::SessionConfig;
pub use tolerance::Tolerance;
pub use tree::Tree;
pub use treenode::TreeNode;
pub use vector::Vector;
pub use graph::Vertex;
pub use xform::Xform;
pub use matrix::Matrix;
pub use convex_hull::ConvexHull;
pub use kdtree::KDTree;
pub use marching_squares::MarchingSquares;
